"""Survey questions configuration for AI in Education survey."""

SECTIONS = [
    {
        "id": "A",
        "title": "Teacher Demographics",
        "description": "Let's start with a few questions about you and your school.",
        "questions": [
            {
                "key": "school_board",
                "question": "What board/affiliation is your school associated with?",
                "type": "single_choice",
                "options": [
                    "CBSE",
                    "ICSE / ISC",
                    "State Board",
                    "IB (International Baccalaureate)",
                    "Cambridge (IGCSE / A-Level)",
                    "Other",
                ],
                "required": True,
            },
            {
                "key": "subjects_taught",
                "question": "Which subject(s) do you teach? (Select all that apply)",
                "type": "multi_choice",
                "options": [
                    "Mathematics",
                    "Science (Physics / Chemistry / Biology)",
                    "English / Language Arts",
                    "Social Studies / History / Geography",
                    "Computer Science / IT",
                    "Hindi / Regional Language",
                    "Commerce / Economics",
                    "Arts / Music / Physical Education",
                    "Other",
                ],
                "required": True,
            },
            {
                "key": "grade_levels",
                "question": "Which grade level(s) do you teach? (Select all that apply)",
                "type": "multi_choice",
                "options": [
                    "Primary (Classes 1-5)",
                    "Middle School (Classes 6-8)",
                    "Secondary (Classes 9-10)",
                    "Senior Secondary (Classes 11-12)",
                ],
                "required": True,
            },
            {
                "key": "experience_years",
                "question": "How many years of teaching experience do you have?",
                "type": "single_choice",
                "options": [
                    "Less than 2 years",
                    "2-5 years",
                    "6-10 years",
                    "11-20 years",
                    "More than 20 years",
                ],
                "required": True,
            },
            {
                "key": "city_tier",
                "question": "Where is your school located?",
                "type": "single_choice",
                "options": [
                    "Metro city (Delhi, Mumbai, Bangalore, Chennai, Kolkata, Hyderabad)",
                    "Tier-2 city (Pune, Jaipur, Lucknow, Ahmedabad, etc.)",
                    "Tier-3 city or smaller town",
                ],
                "required": True,
            },
        ],
    },
    {
        "id": "B",
        "title": "AI Tools You Use",
        "description": "Now let's talk about your experience with AI tools.",
        "questions": [
            {
                "key": "ai_tools_used",
                "question": "Which AI tools have you used for teaching? (Select all that apply)",
                "type": "multi_choice",
                "options": [
                    "ChatGPT / GPT-4",
                    "Google Gemini (formerly Bard)",
                    "Microsoft Copilot",
                    "Khan Academy Khanmigo",
                    "Canva AI (Magic Write, etc.)",
                    "Grammarly",
                    "QuillBot",
                    "DALL-E / Midjourney (image generation)",
                    "School-provided AI platform",
                    "None - I have not used any AI tools",
                    "Other",
                ],
                "required": True,
            },
            {
                "key": "discovery_channel",
                "question": "How did you first learn about using AI for teaching?",
                "type": "single_choice",
                "options": [
                    "Self-exploration",
                    "School training / workshop",
                    "Social media / YouTube",
                    "Peer recommendation from colleagues",
                    "Professional development program",
                    "News / media coverage",
                ],
                "required": True,
            },
            {
                "key": "ai_usage_duration",
                "question": "How long have you been using AI tools in your teaching practice?",
                "type": "single_choice",
                "options": [
                    "I do not use AI tools yet",
                    "Less than 3 months",
                    "3-6 months",
                    "6-12 months",
                    "More than 1 year",
                ],
                "required": True,
            },
        ],
    },
    {
        "id": "C",
        "title": "How Often Do You Use AI?",
        "description": "Rate how often you use AI for each of the following purposes.",
        "questions": [
            {
                "key": "freq_lesson_plans",
                "question": "Creating or refining lesson plans",
                "type": "frequency",
                "options": ["Never", "Rarely (once a month)", "Sometimes (weekly)", "Often (multiple times a week)", "Daily"],
                "required": True,
            },
            {
                "key": "freq_assessments",
                "question": "Generating assessments, quizzes, or question papers",
                "type": "frequency",
                "options": ["Never", "Rarely (once a month)", "Sometimes (weekly)", "Often (multiple times a week)", "Daily"],
                "required": True,
            },
            {
                "key": "freq_personalized",
                "question": "Creating personalized learning materials for different student levels",
                "type": "frequency",
                "options": ["Never", "Rarely (once a month)", "Sometimes (weekly)", "Often (multiple times a week)", "Daily"],
                "required": True,
            },
            {
                "key": "freq_content",
                "question": "Generating classroom content (presentations, worksheets, visual aids)",
                "type": "frequency",
                "options": ["Never", "Rarely (once a month)", "Sometimes (weekly)", "Often (multiple times a week)", "Daily"],
                "required": True,
            },
            {
                "key": "freq_admin",
                "question": "Administrative tasks (report writing, attendance analysis, timetable planning)",
                "type": "frequency",
                "options": ["Never", "Rarely (once a month)", "Sometimes (weekly)", "Often (multiple times a week)", "Daily"],
                "required": True,
            },
            {
                "key": "freq_engagement",
                "question": "Designing student engagement activities (games, projects, discussions)",
                "type": "frequency",
                "options": ["Never", "Rarely (once a month)", "Sometimes (weekly)", "Often (multiple times a week)", "Daily"],
                "required": True,
            },
            {
                "key": "freq_grading",
                "question": "Grading and providing feedback on student work",
                "type": "frequency",
                "options": ["Never", "Rarely (once a month)", "Sometimes (weekly)", "Often (multiple times a week)", "Daily"],
                "required": True,
            },
            {
                "key": "freq_parent_comm",
                "question": "Communicating with parents (drafting messages, translating, report cards)",
                "type": "frequency",
                "options": ["Never", "Rarely (once a month)", "Sometimes (weekly)", "Often (multiple times a week)", "Daily"],
                "required": True,
            },
        ],
    },
    {
        "id": "D",
        "title": "Innovative Uses",
        "description": "Tell us about any creative or unconventional ways you've used AI.",
        "questions": [
            {
                "key": "innovative_uses",
                "question": "Have you used AI in any creative or unconventional ways? (Select all that apply)",
                "type": "multi_choice",
                "options": [
                    "AI-assisted debate or discussion topics",
                    "Students using AI as a learning companion (with supervision)",
                    "Creating multilingual content for diverse classrooms",
                    "Generating real-world problem scenarios for project-based learning",
                    "Using AI for special education / learning disability support",
                    "Creating mock interviews or career guidance content",
                    "None of the above",
                    "Other",
                ],
                "required": True,
            },
            {
                "key": "innovative_desc",
                "question": "Describe any innovative use of AI in your teaching that you are proud of. (Optional)",
                "type": "text",
                "required": False,
            },
        ],
    },
    {
        "id": "E",
        "title": "Impact on Students",
        "description": "How has AI-assisted teaching affected your students? Rate your agreement with each statement.",
        "questions": [
            {
                "key": "impact_learning",
                "question": "AI-assisted teaching has improved my students' learning outcomes.",
                "type": "likert",
                "options": ["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
                "required": True,
            },
            {
                "key": "impact_engagement",
                "question": "Students are more engaged in class when I use AI-generated materials.",
                "type": "likert",
                "options": ["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
                "required": True,
            },
            {
                "key": "impact_individual",
                "question": "AI tools have helped me identify and address individual student weaknesses.",
                "type": "likert",
                "options": ["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
                "required": True,
            },
            {
                "key": "impact_performance",
                "question": "Using AI has positively impacted student performance in exams/assessments.",
                "type": "likert",
                "options": ["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
                "required": True,
            },
            {
                "key": "impact_creativity",
                "question": "AI-enhanced lessons encourage more creativity and critical thinking in students.",
                "type": "likert",
                "options": ["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
                "required": True,
            },
        ],
    },
    {
        "id": "F",
        "title": "Challenges & Support",
        "description": "What barriers do you face, and what support would help?",
        "questions": [
            {
                "key": "barriers",
                "question": "What are the biggest challenges you face in using AI for teaching? (Select all that apply)",
                "type": "multi_choice",
                "options": [
                    "Lack of training or knowledge about AI tools",
                    "Unreliable internet connectivity at school",
                    "School administration does not support AI use",
                    "Concerns about academic integrity / students misusing AI",
                    "AI tools are too expensive (paid subscriptions)",
                    "AI-generated content is not aligned with Indian curriculum (NCERT, etc.)",
                    "Language barriers (tools work better in English than Indian languages)",
                    "Lack of time to learn and integrate AI",
                    "Privacy and data security concerns",
                    "None - I face no significant challenges",
                ],
                "required": True,
            },
            {
                "key": "support_needed",
                "question": "What support would help you use AI more effectively? (Select all that apply)",
                "type": "multi_choice",
                "options": [
                    "Structured training workshops from school",
                    "AI tools designed specifically for Indian curriculum",
                    "Ready-made AI prompt libraries for teachers",
                    "Government or board guidelines on AI in education",
                    "Peer learning communities / teacher forums",
                    "Affordable or free AI tools",
                    "Better internet infrastructure",
                ],
                "required": True,
            },
        ],
    },
    {
        "id": "G",
        "title": "Looking Ahead",
        "description": "Finally, let's talk about the future of AI in your teaching.",
        "questions": [
            {
                "key": "future_likelihood",
                "question": "How likely are you to increase your use of AI in teaching over the next year?",
                "type": "single_choice",
                "options": [
                    "Very unlikely",
                    "Unlikely",
                    "Neutral",
                    "Likely",
                    "Very likely",
                ],
                "required": True,
            },
            {
                "key": "future_priority",
                "question": "Which area would you most like AI to help you with in the future?",
                "type": "single_choice",
                "options": [
                    "Reducing administrative workload",
                    "Creating more engaging lessons",
                    "Personalizing learning for each student",
                    "Improving assessment quality",
                    "Better parent-teacher communication",
                    "Professional development and upskilling",
                ],
                "required": True,
            },
        ],
    },
]

# All question keys in order (used for database schema)
ALL_KEYS = []
for section in SECTIONS:
    for q in section["questions"]:
        ALL_KEYS.append(q["key"])
